
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CalculWebService", targetNamespace = "http://webService.jeeg3webservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculWebService {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustraction", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.Soustraction")
    @ResponseWrapper(localName = "soustractionResponse", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.SoustractionResponse")
    @Action(input = "http://webService.jeeg3webservice.example.com/CalculWebService/soustractionRequest", output = "http://webService.jeeg3webservice.example.com/CalculWebService/soustractionResponse")
    public Double soustraction(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "produit", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.Produit")
    @ResponseWrapper(localName = "produitResponse", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.ProduitResponse")
    @Action(input = "http://webService.jeeg3webservice.example.com/CalculWebService/produitRequest", output = "http://webService.jeeg3webservice.example.com/CalculWebService/produitResponse")
    public Double produit(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.DivisionResponse")
    @Action(input = "http://webService.jeeg3webservice.example.com/CalculWebService/divisionRequest", output = "http://webService.jeeg3webservice.example.com/CalculWebService/divisionResponse")
    public Double division(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.MultiplicationResponse")
    @Action(input = "http://webService.jeeg3webservice.example.com/CalculWebService/multiplicationRequest", output = "http://webService.jeeg3webservice.example.com/CalculWebService/multiplicationResponse")
    public Integer multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "somme", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.Somme")
    @ResponseWrapper(localName = "sommeResponse", targetNamespace = "http://webService.jeeg3webservice.example.com/", className = "proxy.SommeResponse")
    @Action(input = "http://webService.jeeg3webservice.example.com/CalculWebService/sommeRequest", output = "http://webService.jeeg3webservice.example.com/CalculWebService/sommeResponse")
    public Integer somme(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
