
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculWebServiceService", targetNamespace = "http://webService.jeeg3webservice.example.com/", wsdlLocation = "http://localhost:8088/?wsdl")
public class CalculWebServiceService
    extends Service
{

    private static final URL CALCULWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException CALCULWEBSERVICESERVICE_EXCEPTION;
    private static final QName CALCULWEBSERVICESERVICE_QNAME = new QName("http://webService.jeeg3webservice.example.com/", "CalculWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULWEBSERVICESERVICE_WSDL_LOCATION = url;
        CALCULWEBSERVICESERVICE_EXCEPTION = e;
    }

    public CalculWebServiceService() {
        super(__getWsdlLocation(), CALCULWEBSERVICESERVICE_QNAME);
    }

    public CalculWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULWEBSERVICESERVICE_QNAME, features);
    }

    public CalculWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULWEBSERVICESERVICE_QNAME);
    }

    public CalculWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULWEBSERVICESERVICE_QNAME, features);
    }

    public CalculWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculWebService
     */
    @WebEndpoint(name = "CalculWebServicePort")
    public CalculWebService getCalculWebServicePort() {
        return super.getPort(new QName("http://webService.jeeg3webservice.example.com/", "CalculWebServicePort"), CalculWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculWebService
     */
    @WebEndpoint(name = "CalculWebServicePort")
    public CalculWebService getCalculWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.jeeg3webservice.example.com/", "CalculWebServicePort"), CalculWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULWEBSERVICESERVICE_EXCEPTION!= null) {
            throw CALCULWEBSERVICESERVICE_EXCEPTION;
        }
        return CALCULWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
